server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: messages
  security:
    user:
      name: sung
      password: pass1234

management:
  endpoints:
    web:
      exposure:
        include: "*"

